services:
    #Start of Earnapp section (remove this if Earnapp not wanted)
    Earnapp:
        image: fazalfarhan01/earnapp:lite
        volumes:
            - earnapp-data:/etc/earnapp
        restart: always
        environment:
            - EARNAPP_UUID=$EARNAPP_DEVICE_ID
        networks:
            default:
                ipv4_address: 172.106.0.20
    #End of Earnapp section


    #Start of HoneyGain section (remove this if HoneyGain not wanted)
    Honeygain:
        image: honeygain/honeygain
        command: -tou-accept -email $HONEYGAIN_EMAIL -pass '$HONEYGAIN_PASSWD' -device $DEVICE_NAME
        restart: always
        networks:
            default:
                ipv4_address: 172.106.0.30
    #End of HoneyGain section

    #Start of IproyalPawns section (remove this if IproyalPawns not wanted)
    IproyalPawns:
        image: iproyal/pawns-cli:latest
        command: -email=$IPROYALPAWNS_EMAIL -password='$IPROYALPAWNS_PASSWD' -device-name=$DEVICE_NAME -accept-tos
        restart: always
        networks:
            default:
                ipv4_address: 172.106.0.40
    #End of IproyalPawns section

    #Start of Peer2profit section (remove this if Peer2profit not wanted)
    Peer2profit:
        image: enwaiax/peer2profit:latest
        restart: always
        environment:
            - email=$PEER2PROFIT_EMAIL
            - use_proxy=false
        networks:
            default:
                ipv4_address: 172.106.0.50
    #End of Peer2profit section

    #Start of Packetstream section (remove this if Packetstream not wanted)
    Packetstream_PsClient:
        image: packetstream/psclient:latest
        restart: always
        environment:
            - CID=$PACKETSTREAM_CID
        networks:
            default:
                ipv4_address: 172.106.0.60
    Packetstream_Watchtower:
            - Packetstream_PsClient
        image: containrrr/watchtower
        command: --cleanup --include-stopped --revive-stopped --interval 60 --scope PacketStream ${_COMPOSE_PROJECT_NAME}_Packetstream_PsClient_${_COMPOSE_PROJECT_STACK_ID}
        labels:
            - com.centurylinklabs.watchtower.scope=PacketStream
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        restart: always
        networks:
            default:
                ipv4_address: 172.106.0.61
    #End of Packetstream section
    
    #Start of Bitping section (remove this if Bitping not wanted)
    Bitping:
        image: bitping/bitping-node:latest
        restart: always
        volumes:
            - ./data/bitping:/root/.bitping
        networks:
            default:
                ipv4_address: 172.106.0.70
    #End of Bitping section     

    #Start of TraffMonetizer section (remove this if TraffMonetizer not wanted)
    TraffMonetizer:
        image: traffmonetizer/cli_v2:latest
        restart: always
        command: start accept --token ${TRAFFMONETIZER_TOKEN}
        networks:
            default:
                ipv4_address: 172.106.0.80
    #End of Packetstream section   
    
    #Start of Repocket section (remove this if Repocket not wanted)
    Repocket:
        image: repocket/repocket:latest
        restart: always
        environment:
          - RP_EMAIL
          - RP_API_KEY
        networks:
            default:
                ipv4_address: 172.106.0.90
    #End of Repocket section    

    #Start of Proxylite section (remove this if Proxylite not wanted)
    Proxylite:
        image: proxylite/proxyservice:latest
        restart: always
        environment:
          - USER_ID=$PROXYLITE_USER_ID
        networks:
            default:
                ipv4_address: 172.106.0.100
    #End of Proxylite section 

    #Start of Proxyrack section (remove this if Proxyrack not wanted)
    Proxyrack:
        image: proxyrack/pop:latest
        restart: always
        environment:
          - UUID=$PROXYRACK_HOST_UUID
        networks:
            default:
                ipv4_address: 172.106.0.110
    #End of Proxyrack section 

    #Start of EarnFm section (remove this if EarnFm not wanted)
    EarnFm_Client:
        image: earnfm/earnfm-client:latest
        restart: always
        environment:
            - EARNFM_TOKEN=$EARNFM_APIKEY
        networks:
            default:
                ipv4_address: 172.106.0.130
    EarnFm_Watchtower:
            - EarnFm_Client
        image: containrrr/watchtower
        command: --cleanup --include-stopped --revive-stopped --interval 60 --scope EarnFm ${_COMPOSE_PROJECT_NAME}_EarnFm_Client_${_COMPOSE_PROJECT_STACK_ID}
        labels:
            - com.centurylinklabs.watchtower.scope=EarnFm
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        restart: always
        networks:
            default:
                ipv4_address: 172.106.0.131
    #End of EarnFm section


volumes:
    earnapp-data:

networks:
    default:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 172.106.0.0/16
